[package]
name = "rust-simple-crud"
version = "0.1.0"
authors = ["Alexander Zenov <alexander.zenov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
